spring:
  application:
    name: User
  redis:
    # 内网地址 r-2ze9pwtzkww18g31rd.redis.rds.aliyuncs.com
    host: localhost
    port: 6379
    password: 1234
    database: 15
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/wangwen?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream #访问/actuator/hystrix.stream能看到不断更新的监控流